### ISSUE TITLE
Ability to play multiple songs

### ISSUE THREAD

**Issue by toma** [toma/robotband#2]
Read the setlist and play multiple songs with the ability to navigate between them

Load Setlist
Read line by line into array
While setlist array has entries
	Open file pointing at setlist[i]
		Read until next \n every time get pianoRoll.nextLine is called until it's empty
		Set state set values
		Set delay
		When no more entries, stop and wait until signal to play next song is received
---------------		

Performance
	init::
		build setlist
	shred::
		Setlist::playSongsInOrder()
	
	Interrupt registered for playPreviousSong() and playNextSong() methods
	
Setlist
	init::
		load setlist.csv into string array
		create piano roll
	playSongsInOrder::
		Play setlist[0]
			pianoRoll::loadFile(setlist[0])
			pianoRoll::readLine()
			musician->setState(pianoRoll.getStateSet())
			delay(pianoRoll.getDelay())
			
			Open file pointing at song1.csv
				while file still has contents, 
					readUntilStream('\n') for song1, parse into delay, left arm, right arm every time piano

**Comment by toma** [comment]
This was handled when adding the ability to play the songs from Serial input, closing.

**Comment by themetalmystic** [comment]
:8ball: :muscle:
